name: Middleman

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        with:
          REMOTE_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CNAME_DOMAIN: ferperales.net
        uses: ferperales/middleman-gh-pages-action@v1.0.0
